# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ticketuser
quarkus.datasource.password=ticketpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ticketdb

# Hibernate: crea y actualiza tablas automáticamente
quarkus.hibernate-orm.database.generation=update

# Puerto
quarkus.http.port=8080

# CORS para Angular
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200

# Swagger UI siempre visible (no solo en dev)
quarkus.swagger-ui.always-include=true
